Update deploy.yml

diff --git a/deploy.yml b/deploy.yml
--- a/deploy.yml
+++ b/deploy.yml
@@ -9,11 +9,20 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
+
       - name: Replace secrets
         run: |
-          sed -i "s/#{GOOGLE_CLIENT_ID}#/${{ secrets.GOOGLE_CLIENT_ID }}/g" index.html
-          sed -i "s/#{GOOGLE_API_KEY}#/${{ secrets.GOOGLE_API_KEY }}/g" index.html
-          sed -i "s/#{GOOGLE_SHEET_ID}#/${{ secrets.GOOGLE_SHEET_ID }}/g" index.html
+          echo "Replacing API credentials..."
+          sed -i "s|#{GOOGLE_CLIENT_ID}#|${{ secrets.GOOGLE_CLIENT_ID }}|g" index.html
+          sed -i "s|#{GOOGLE_API_KEY}#|${{ secrets.GOOGLE_API_KEY }}|g" index.html
+          sed -i "s|#{GOOGLE_SHEET_ID}#|${{ secrets.GOOGLE_SHEET_ID }}|g" index.html
+          
+          echo "Checking replacements..."
+          if grep -q "#{GOOGLE_" index.html; then
+            echo "Error: Found unreplaced values"
+            exit 1
+          fi
+
       - name: Deploy
         uses: JamesIves/github-pages-deploy-action@4.1.5
         with:
